name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: set -x; npm install --prefix portfolio

      - name: Build project
        run: set -x; npm run build --prefix portfolio

      - name: Export project
        run: set -x; npm run next export --prefix portfolio

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portfolio/out